import type { RegisteredAsset } from "./registry.js";

/** The xStocks universe on Solana, issued by Backed.
 *
 *  Every entry here was verified against Solana mainnet before it was added:
 *  the mint account parses as an SPL Token-2022 mint, and the name and symbol
 *  below are the ones written into the mint's own metadata extension, not a
 *  label taken from a token list. referenceTicker is the symbol without its
 *  trailing "x", and each mint was confirmed to have a reference price
 *  published against it.
 *
 *  Re-verify the whole file at any time with `npm run verify-assets`, which
 *  reads every mint back from the chain and reports anything that drifted.
 *
 *  assetType splits on what the token tracks: "fund" for index, treasury,
 *  commodity, and fund shares, "tokenized_equity" for shares in a company. */
export const XSTOCKS: RegisteredAsset[] = [
  {
    id: "asset_aaplx",
    symbol: "AAPLx",
    name: "Apple xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp",
    decimals: 8,
    referenceTicker: "AAPL",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_abbvx",
    symbol: "ABBVx",
    name: "AbbVie xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XswbinNKyPmzTa5CskMbCPvMW6G5CMnZXZEeQSSQoie",
    decimals: 8,
    referenceTicker: "ABBV",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_abtx",
    symbol: "ABTx",
    name: "Abbott xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsHtf5RpxsQ7jeJ9ivNewouZKJHbPxhPoEy6yYvULr7",
    decimals: 8,
    referenceTicker: "ABT",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_acnx",
    symbol: "ACNx",
    name: "Accenture xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xs5UJzmCRQ8DWZjskExdSQDnbE6iLkRu2jjrRAB1JSU",
    decimals: 8,
    referenceTicker: "ACN",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_ambrx",
    symbol: "AMBRx",
    name: "Amber xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsaQTCgebC2KPbf27KUhdv5JFvHhQ4GDAPURwrEhAzb",
    decimals: 8,
    referenceTicker: "AMBR",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_amdx",
    symbol: "AMDx",
    name: "AMD xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsXcJ6GZ9kVnjqGsjBnktRcuwMBmvKWh8S93RefZ1rF",
    decimals: 8,
    referenceTicker: "AMD",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_amznx",
    symbol: "AMZNx",
    name: "Amazon.com xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg",
    decimals: 8,
    referenceTicker: "AMZN",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_appx",
    symbol: "APPx",
    name: "AppLovin xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsPdAVBi8Zc1xvv53k4JcMrQaEDTgkGqKYeh7AYgPHV",
    decimals: 8,
    referenceTicker: "APP",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_avgox",
    symbol: "AVGOx",
    name: "Broadcom xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsgSaSvNSqLTtFuyWPBhK9196Xb9Bbdyjj4fH3cPJGo",
    decimals: 8,
    referenceTicker: "AVGO",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_aznx",
    symbol: "AZNx",
    name: "AstraZeneca xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xs3ZFkPYT2BN7qBMqf1j1bfTeTm1rFzEFSsQ1z3wAKU",
    decimals: 8,
    referenceTicker: "AZN",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_bacx",
    symbol: "BACx",
    name: "Bank of America xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XswsQk4duEQmCbGzfqUUWYmi7pV7xpJ9eEmLHXCaEQP",
    decimals: 8,
    referenceTicker: "BAC",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_brkbx",
    symbol: "BRK.Bx",
    name: "Berkshire Hathaway xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xs6B6zawENwAbWVi7w92rjazLuAr5Az59qgWKcNb45x",
    decimals: 8,
    referenceTicker: "BRK.B",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_cmcsax",
    symbol: "CMCSAx",
    name: "Comcast xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsvKCaNsxg2GN8jjUmq71qukMJr7Q1c5R2Mk9P8kcS8",
    decimals: 8,
    referenceTicker: "CMCSA",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_coinx",
    symbol: "COINx",
    name: "Coinbase xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu",
    decimals: 8,
    referenceTicker: "COIN",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_crclx",
    symbol: "CRCLx",
    name: "Circle xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1",
    decimals: 8,
    referenceTicker: "CRCL",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_crmx",
    symbol: "CRMx",
    name: "Salesforce xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsczbcQ3zfcgAEt9qHQES8pxKAVG5rujPSHQEXi4kaN",
    decimals: 8,
    referenceTicker: "CRM",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_crwdx",
    symbol: "CRWDx",
    name: "CrowdStrike xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xs7xXqkcK7K8urEqGg52SECi79dRp2cEKKuYjUePYDw",
    decimals: 8,
    referenceTicker: "CRWD",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_cscox",
    symbol: "CSCOx",
    name: "Cisco xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xsr3pdLQyXvDJBFgpR5nexCEZwXvigb8wbPYp4YoNFf",
    decimals: 8,
    referenceTicker: "CSCO",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_cvxx",
    symbol: "CVXx",
    name: "Chevron xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsNNMt7WTNA2sV3jrb1NNfNgapxRF5i4i6GcnTRRHts",
    decimals: 8,
    referenceTicker: "CVX",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_dfdvx",
    symbol: "DFDVx",
    name: "DFDV xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xs2yquAgsHByNzx68WJC55WHjHBvG9JsMB7CWjTLyPy",
    decimals: 8,
    referenceTicker: "DFDV",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_dhrx",
    symbol: "DHRx",
    name: "Danaher xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xseo8tgCZfkHxWS9xbFYeKFyMSbWEvZGFV1Gh53GtCV",
    decimals: 8,
    referenceTicker: "DHR",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_gevx",
    symbol: "GEVx",
    name: "GE Vernova Inc. xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XswXzAsMV9kebQjCVtr1btvrQgQ7C4C9kKgH4QYAVzw",
    decimals: 8,
    referenceTicker: "GEV",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_gldx",
    symbol: "GLDx",
    name: "Gold xStock",
    assetType: "fund",
    chain: "solana",
    mint: "Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re",
    decimals: 8,
    referenceTicker: "GLD",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_gmex",
    symbol: "GMEx",
    name: "Gamestop xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xsf9mBktVB9BSU5kf4nHxPq5hCBJ2j2ui3ecFGxPRGc",
    decimals: 8,
    referenceTicker: "GME",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_googlx",
    symbol: "GOOGLx",
    name: "Alphabet xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN",
    decimals: 8,
    referenceTicker: "GOOGL",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_gsx",
    symbol: "GSx",
    name: "Goldman Sachs xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsgaUyp4jd1fNBCxgtTKkW64xnnhQcvgaxzsbAq5ZD1",
    decimals: 8,
    referenceTicker: "GS",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_hdx",
    symbol: "HDx",
    name: "Home Depot xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XszjVtyhowGjSC5odCqBpW1CtXXwXjYokymrk7fGKD3",
    decimals: 8,
    referenceTicker: "HD",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_honx",
    symbol: "HONx",
    name: "Honeywell xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsRbLZthfABAPAfumWNEJhPyiKDW6TvDVeAeW7oKqA2",
    decimals: 8,
    referenceTicker: "HON",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_hoodx",
    symbol: "HOODx",
    name: "Robinhood xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg",
    decimals: 8,
    referenceTicker: "HOOD",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_ibmx",
    symbol: "IBMx",
    name: "International Business Machines xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XspwhyYPdWVM8XBHZnpS9hgyag9MKjLRyE3tVfmCbSr",
    decimals: 8,
    referenceTicker: "IBM",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_iemgx",
    symbol: "IEMGx",
    name: "Core MSCI Emerging Markets xStock",
    assetType: "fund",
    chain: "solana",
    mint: "XsFnZawJdLdXfBSEt5Vw29K5vdBiHotdPLjUPafpfHs",
    decimals: 8,
    referenceTicker: "IEMG",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_intcx",
    symbol: "INTCx",
    name: "Intel xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XshPgPdXFRWB8tP1j82rebb2Q9rPgGX37RuqzohmArM",
    decimals: 8,
    referenceTicker: "INTC",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_jnjx",
    symbol: "JNJx",
    name: "Johnson & Johnson xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsGVi5eo1Dh2zUpic4qACcjuWGjNv8GCt3dm5XcX6Dn",
    decimals: 8,
    referenceTicker: "JNJ",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_jpmx",
    symbol: "JPMx",
    name: "JPMorgan Chase xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsMAqkcKsUewDrzVkait4e5u4y8REgtyS7jWgCpLV2C",
    decimals: 8,
    referenceTicker: "JPM",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_kox",
    symbol: "KOx",
    name: "Coca-Cola xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsaBXg8dU5cPM6ehmVctMkVqoiRG2ZjMo1cyBJ3AykQ",
    decimals: 8,
    referenceTicker: "KO",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_linx",
    symbol: "LINx",
    name: "Linde xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsSr8anD1hkvNMu8XQiVcmiaTP7XGvYu7Q58LdmtE8Z",
    decimals: 8,
    referenceTicker: "LIN",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_llyx",
    symbol: "LLYx",
    name: "Eli Lilly xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xsnuv4omNoHozR6EEW5mXkw8Nrny5rB3jVfLqi6gKMH",
    decimals: 8,
    referenceTicker: "LLY",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_max",
    symbol: "MAx",
    name: "Mastercard xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsApJFV9MAktqnAc6jqzsHVujxkGm9xcSUffaBoYLKC",
    decimals: 8,
    referenceTicker: "MA",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_mcdx",
    symbol: "MCDx",
    name: "McDonald's xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2",
    decimals: 8,
    referenceTicker: "MCD",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_mdtx",
    symbol: "MDTx",
    name: "Medtronic xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsDgw22qRLTv5Uwuzn6T63cW69exG41T6gwQhEK22u2",
    decimals: 8,
    referenceTicker: "MDT",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_metax",
    symbol: "METAx",
    name: "Meta xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu",
    decimals: 8,
    referenceTicker: "META",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_mrkx",
    symbol: "MRKx",
    name: "Merck xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsnQnU7AdbRZYe2akqqpibDdXjkieGFfSkbkjX1Sd1X",
    decimals: 8,
    referenceTicker: "MRK",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_mrvlx",
    symbol: "MRVLx",
    name: "Marvell xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsuxRGDzbLjnJ72v74b7p9VY6N66uYgTCyfwwRjVCJA",
    decimals: 8,
    referenceTicker: "MRVL",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_msftx",
    symbol: "MSFTx",
    name: "Microsoft xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX",
    decimals: 8,
    referenceTicker: "MSFT",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_mstrx",
    symbol: "MSTRx",
    name: "MicroStrategy xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ",
    decimals: 8,
    referenceTicker: "MSTR",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_nflxx",
    symbol: "NFLXx",
    name: "Netflix xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsEH7wWfJJu2ZT3UCFeVfALnVA6CP5ur7Ee11KmzVpL",
    decimals: 8,
    referenceTicker: "NFLX",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_nvdax",
    symbol: "NVDAx",
    name: "NVIDIA xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh",
    decimals: 8,
    referenceTicker: "NVDA",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_openx",
    symbol: "OPENx",
    name: "OPEN xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsGtpmjhmC8kyjVSWL4VicGu36ceq9u55PTgF8bhGv6",
    decimals: 8,
    referenceTicker: "OPEN",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_orclx",
    symbol: "ORCLx",
    name: "Oracle xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsjFwUPiLofddX5cWFHW35GCbXcSu1BCUGfxoQAQjeL",
    decimals: 8,
    referenceTicker: "ORCL",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_pepx",
    symbol: "PEPx",
    name: "PepsiCo xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xsv99frTRUeornyvCfvhnDesQDWuvns1M852Pez91vF",
    decimals: 8,
    referenceTicker: "PEP",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_pfex",
    symbol: "PFEx",
    name: "Pfizer xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsAtbqkAP1HJxy7hFDeq7ok6yM43DQ9mQ1Rh861X8rw",
    decimals: 8,
    referenceTicker: "PFE",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_pgx",
    symbol: "PGx",
    name: "Procter & Gamble xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsYdjDjNUygZ7yGKfQaB6TxLh2gC6RRjzLtLAGJrhzV",
    decimals: 8,
    referenceTicker: "PG",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_pltrx",
    symbol: "PLTRx",
    name: "Palantir xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsoBhf2ufR8fTyNSjqfU71DYGaE6Z3SUGAidpzriAA4",
    decimals: 8,
    referenceTicker: "PLTR",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_pmx",
    symbol: "PMx",
    name: "Philip Morris xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xsba6tUnSjDae2VcopDB6FGGDaxRrewFCDa5hKn5vT3",
    decimals: 8,
    referenceTicker: "PM",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_ppltx",
    symbol: "PPLTx",
    name: "abrdn Physical Platinum Shares xStock",
    assetType: "fund",
    chain: "solana",
    mint: "Xst6eFD4YT6sz9RLMysN9SyvaZWtraSdVJQGu5ZkAme",
    decimals: 8,
    referenceTicker: "PPLT",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_qqqx",
    symbol: "QQQx",
    name: "Nasdaq xStock",
    assetType: "fund",
    chain: "solana",
    mint: "Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ",
    decimals: 8,
    referenceTicker: "QQQ",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_spcxx",
    symbol: "SPCXx",
    name: "SpaceX xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xs3oZwbHvqis4NYcf4YKWmEia2eC84wSiVrcYcTqpH8",
    decimals: 8,
    referenceTicker: "SPCX",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_spyx",
    symbol: "SPYx",
    name: "SP500 xStock",
    assetType: "fund",
    chain: "solana",
    mint: "XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W",
    decimals: 8,
    referenceTicker: "SPY",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_strcx",
    symbol: "STRCx",
    name: "Strategy PP Variable xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xs78JED6PFZxWc2wCEPspZW9kL3Se5J7L5TChKgsidH",
    decimals: 8,
    referenceTicker: "STRC",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_tbllx",
    symbol: "TBLLx",
    name: "TBLL xStock",
    assetType: "fund",
    chain: "solana",
    mint: "XsqBC5tcVQLYt8wqGCHRnAUUecbRYXoJCReD6w7QEKp",
    decimals: 8,
    referenceTicker: "TBLL",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_tmox",
    symbol: "TMOx",
    name: "Thermo Fisher xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xs8drBWy3Sd5QY3aifG9kt9KFs2K3PGZmx7jWrsrk57",
    decimals: 8,
    referenceTicker: "TMO",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_tmusx",
    symbol: "TMUSx",
    name: "T-Mobile xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XswCi2U1G6Ppbw1QhG45yKb8UKuR1FKLJrquv2FZSD4",
    decimals: 8,
    referenceTicker: "TMUS",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_tqqqx",
    symbol: "TQQQx",
    name: "TQQQ xStock",
    assetType: "fund",
    chain: "solana",
    mint: "XsjQP3iMAaQ3kQScQKthQpx9ALRbjKAjQtHg6TFomoc",
    decimals: 8,
    referenceTicker: "TQQQ",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_tslax",
    symbol: "TSLAx",
    name: "Tesla xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB",
    decimals: 8,
    referenceTicker: "TSLA",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_tsmx",
    symbol: "TSMx",
    name: "TSMC xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsafvsGtzFqqHgTnA3aPC83EAMkacU5mcGtcSayhpVV",
    decimals: 8,
    referenceTicker: "TSM",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_uberx",
    symbol: "UBERx",
    name: "Uber xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsAsZLF4MmsvS1sDxRMrUz7REjHfwbC9UAMXSRBqgEB",
    decimals: 8,
    referenceTicker: "UBER",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_unhx",
    symbol: "UNHx",
    name: "UnitedHealth xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XszvaiXGPwvk2nwb3o9C1CX4K6zH8sez11E6uyup6fe",
    decimals: 8,
    referenceTicker: "UNH",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_vcxx",
    symbol: "VCXx",
    name: "Fundrise Innovation Fund, LLC xStock",
    assetType: "fund",
    chain: "solana",
    mint: "Xs7UsqobM3EJgMeHwdAbmDBCZH1G5WTCjatpeYcCr8x",
    decimals: 8,
    referenceTicker: "VCX",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_vtix",
    symbol: "VTIx",
    name: "Vanguard xStock",
    assetType: "fund",
    chain: "solana",
    mint: "XsssYEQjzxBCFgvYFFNuhJFBeHNdLWYeUSP8F45cDr9",
    decimals: 8,
    referenceTicker: "VTI",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_vx",
    symbol: "Vx",
    name: "Visa xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsqgsbXwWogGJsNcVZ3TyVouy2MbTkfCFhCGGGcQZ2p",
    decimals: 8,
    referenceTicker: "V",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_wmtx",
    symbol: "WMTx",
    name: "Walmart xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "Xs151QeqTCiuKtinzfRATnUESM2xTU6V9Wy8Vy538ci",
    decimals: 8,
    referenceTicker: "WMT",
    issuerName: "Backed Assets",
  },
  {
    id: "asset_xomx",
    symbol: "XOMx",
    name: "Exxon Mobil xStock",
    assetType: "tokenized_equity",
    chain: "solana",
    mint: "XsaHND8sHyfMfsWPj6kSdd5VwvCayZvjYgKmmcNL5qh",
    decimals: 8,
    referenceTicker: "XOM",
    issuerName: "Backed Assets",
  },
];
